apiVersion: webapp.attgua.dev/v1
kind: GuestBook
metadata:
  labels:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/instance: guestbook-sample
    app.kubernetes.io/part-of: gooperator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gooperator
  name: guestbook-sample
spec:
  # TODO(user): Add fields here
  redisName: redis-sample
  frontend:
    resources:
      requests:
        cpu: 50m
    servingPort: -1